version: "2"

services:
  mariadb:
    image: mariadb:latest
    container_name: db
    restart: always
    networks:
      - network_birgitta
    volumes:
      - mariadb_birgitta:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpswd
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - network_birgitta
    ports:
      - "8080:80"
    links:
      - mariadb:db

  omeka:
    depends_on:
      - mariadb
    # image: wruiwr/omeka-s-birgitta:latest
    build: .
    restart: always
    networks:
      - network_birgitta
    ports:
      - "80:80"
    links:
      - mariadb:db
    volumes:
      - birgitta:/var/www/html/volume

volumes:
  mariadb_birgitta:
  birgitta:

networks:
  network_birgitta:
