name: Manually Build and Push Docker Image

on: workflow_dispatch # run manually
  #  inputs:
  #    tag:
  #      description: 'Docker image tag'
  #      required: true
  #      default: 'latest'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # This dynamically references the branch you trigger the workflow from

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          #username: ${{ github.repository_owner }}
          #password: ${{ secrets.PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/your-image-name:${{ github.run_id }}  # Tagging with run_id for uniqueness

      
