name: Manually deploy Kubernetes secrets for dev environment

on: workflow_dispatch # run manually

jobs:
  deploy-kube-secrets-dev:
    name: Deploy Kubernetes secrets to dev environment
    environment:
      name: Kube-secrets-dev
    runs-on: ubuntu-latest

    steps:
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3

      - name: Setup kubectl
        env:
          MICROK8S_CONFIG: ${{ secrets.MICROK8S_CONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${MICROK8S_CONFIG}" | base64 --decode > $HOME/.kube/config

      - name: Check kubectl get node
        run: kubectl get nodes -o wide

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: deploy Kubernetes secrets to dev environment
        run: |
          # create secret regcred for kubernetes to pull image from private registry on Github
          if ! kubectl -n dev get secret regcred; then
            # create the secret when no secret is found
            echo "${{ github.actor }}"
            echo "${{ secrets.PAT }}"
            kubectl -n dev create secret docker-registry regcred --docker-username=${{ github.actor }} --docker-password=${{ secrets.PAT }} --docker-server=ghcr.io
          else
            # check if kubernetes secret regcred needs an update, and update it when it is not the same as given secret GHCR_PAT from Github repository secret
            existing_pass=$(kubectl -n dev get secret regcred --template='{{index .data ".dockerconfigjson" | base64decode}}' | jq -r '.auths["ghcr.io"].password')
            if [[ "$existing_pass" != "${{ secrets.PAT }}" ]]; then
              echo "Updating kubernetes secret as password from Github repository secret does not match."
              kubectl -n dev delete secret regcred
              kubectl -n dev create secret docker-registry regcred --docker-username=${{ github.actor }} --docker-password=${{ secrets.PAT }} --docker-server=ghcr.io
            else
              echo "Secret regcred already exists, and it is the same as GHCR_PAT Github repository secret, skipping."
            fi
          fi
