name: Docker Image Ci for GHCR

on:
  push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-v3.1.1

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}  # This dynamically references the branch you trigger the workflow from
          
      - name: build and push the image
        run: | 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin 
          docker build . --tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          
      
